import type { AuditResult, Finding } from "./types";

function severityEmoji(f: Finding): string {
  if (f.status === "pass") return "✅";
  if (f.status === "needs_review") return "🔍";
  if (f.status === "warning") return "⚠️";
  return "❌";
}

function sectionHeader(title: string) {
  return `\n## ${title}\n`;
}

function renderFinding(f: Finding): string {
  const lines = [
    `### ${severityEmoji(f.status === "fail" ? f : f)} ${f.title}`,
    `- **Category:** ${f.category}`,
    `- **Severity:** ${f.severity}`,
    `- **Status:** ${f.status}`,
  ];
  if (f.pageUrl) lines.push(`- **Page:** ${f.pageUrl}`);
  if (f.evidence.length > 0) {
    lines.push("- **Evidence:**");
    for (const e of f.evidence) {
      lines.push(`  - ${e}`);
    }
  }
  if (f.recommendation) {
    lines.push(`- **Recommendation:** ${f.recommendation}`);
  }
  return lines.join("\n");
}

export function generateMarkdownReport(result: AuditResult): string {
  const criticals = result.findings.filter((f) => f.severity === "CRITICAL" && f.status === "fail");
  const required = result.findings.filter((f) => f.severity === "REQUIRED" && f.status === "fail");
  const warnings = result.findings.filter(
    (f) => (f.status === "warning" || (f.severity === "VERIFY" && f.status === "fail"))
  );
  const humanReview = result.humanReviewItems;

  const lines: string[] = [
    "# LP Draft QA Scanner Report",
    "",
    `> ⚠️ **This is an automated pre-QA scan and does NOT replace QA team review.**`,
    `> It is a pre-flight orientation tool to catch obvious issues before handoff.`,
    "",
    `- **URL:** ${result.url}`,
    `- **Scan Date:** ${new Date(result.scannedAt).toLocaleString()}`,
    `- **Overall Score:** ${result.overallScore}/100`,
    `- **Pages Scanned:** ${result.metadata.pagesSucceeded} of ${result.metadata.pagesAttempted} attempted`,
    `- **Duration:** ${(result.metadata.durationMs / 1000).toFixed(1)}s`,
    "",
    sectionHeader("Summary"),
    `| Severity | Count |`,
    `|---|---|`,
    `| 🔴 Critical fails | ${criticals.length} |`,
    `| 🟠 Required fixes | ${required.length} |`,
    `| 🟡 Warnings | ${warnings.length} |`,
    `| 🔍 Human review | ${humanReview.length} |`,
    "",
  ];

  if (criticals.length > 0) {
    lines.push(sectionHeader("🔴 Critical Issues"));
    lines.push("*These are likely to cause QA passback.*");
    for (const f of criticals) lines.push(renderFinding(f), "");
  }

  if (required.length > 0) {
    lines.push(sectionHeader("🟠 Required Fixes"));
    lines.push("*Must be corrected before handoff.*");
    for (const f of required) lines.push(renderFinding(f), "");
  }

  if (warnings.length > 0) {
    lines.push(sectionHeader("🟡 Warnings"));
    for (const f of warnings) lines.push(renderFinding(f), "");
  }

  if (humanReview.length > 0) {
    lines.push(sectionHeader("🔍 Human Review Required"));
    lines.push(
      "*The following items cannot be reliably verified from URL alone and require manual inspection.*"
    );
    for (const f of humanReview) lines.push(renderFinding(f), "");
  }

  const passing = result.findings.filter(
    (f) => f.status === "pass" && f.severity !== "HUMAN_REVIEW"
  );
  if (passing.length > 0) {
    lines.push(sectionHeader(`✅ Passing Checks (${passing.length})`));
    for (const f of passing) {
      lines.push(`- **${f.category}:** ${f.title}${f.pageUrl ? ` — ${f.pageUrl}` : ""}`);
    }
  }

  lines.push("", "---");
  lines.push(
    "*Generated by LP Draft QA Scanner — an internal pre-QA tool for Luxury Presence Website Builders.*"
  );
  lines.push(
    "*This report is guidance only and does not constitute official QA team approval.*"
  );

  return lines.join("\n");
}

export function generateCsvReport(result: AuditResult): string {
  const header = "Category,Rule ID,Title,Severity,Status,Page URL,Evidence,Recommendation";
  const allFindings = [...result.findings, ...result.humanReviewItems];
  const rows = allFindings.map((f) => {
    const cols = [
      f.category,
      f.id,
      f.title,
      f.severity,
      f.status,
      f.pageUrl ?? "",
      f.evidence.join(" | "),
      f.recommendation,
    ].map((c) => `"${String(c).replace(/"/g, '""')}"`);
    return cols.join(",");
  });
  return [header, ...rows].join("\n");
}
