import type { AuditCategory, Severity } from "./types";

export interface RubricItem {
  id: string;
  category: AuditCategory;
  title: string;
  description: string;
  severity: Severity;
  automatable: boolean;
}

export const RUBRIC: RubricItem[] = [
  // ── CLIENT REQUESTS ──────────────────────────────────────────────────────
  {
    id: "expected-pages-found",
    category: "Client Requests",
    title: "Expected pages present",
    description: "All requested pages from onboarding should be present",
    severity: "CRITICAL",
    automatable: true,
  },
  {
    id: "expected-agents-found",
    category: "Client Requests",
    title: "Expected agents present",
    description: "Every agent specified in onboarding should have a visible presence",
    severity: "CRITICAL",
    automatable: true,
  },
  {
    id: "expected-neighborhoods-found",
    category: "Client Requests",
    title: "Expected neighborhoods present",
    description: "Every neighborhood called out by the client should be present",
    severity: "CRITICAL",
    automatable: true,
  },
  {
    id: "expected-email-found",
    category: "Client Requests",
    title: "Expected email visible",
    description: "Provided email address should appear on site",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "expected-phone-found",
    category: "Client Requests",
    title: "Expected phone visible",
    description: "Provided phone number should appear on site",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "onboarding-requests-delivered",
    category: "Client Requests",
    title: "All onboarding requests delivered",
    description: "Every specific content ask from onboarding hub must be verified manually",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── BRANDING & IDENTITY ───────────────────────────────────────────────────
  {
    id: "favicon-exists",
    category: "Branding & Identity",
    title: "Custom favicon set",
    description: "A custom favicon should be uploaded (not default LP/template favicon)",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "no-placeholder-images",
    category: "Branding & Identity",
    title: "No placeholder/default images",
    description: "No suspicious placeholder filenames or default stock images",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "color-palette-human-review",
    category: "Branding & Identity",
    title: "Color palette matches brand",
    description: "Primary, accent, and background colors must match client style guide — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  {
    id: "typography-human-review",
    category: "Branding & Identity",
    title: "Typography correct",
    description: "Brokerage-required fonts and headline/body fonts must match moodboard/spec — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  {
    id: "capitalization-consistent",
    category: "Branding & Identity",
    title: "Capitalization consistent site-wide",
    description: "Title Case, ALL CAPS, or Sentence case should be applied consistently across titles, nav, CTAs",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── GLOBAL ELEMENTS ──────────────────────────────────────────────────────
  {
    id: "header-nav-links-exist",
    category: "Global Elements",
    title: "Header navigation links exist",
    description: "The header should contain at least one navigation link",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "footer-contact-exists",
    category: "Global Elements",
    title: "Footer contact information present",
    description: "Footer should contain phone, email, or address",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "contact-info-consistency",
    category: "Global Elements",
    title: "Contact info consistent site-wide",
    description: "Phone and email should match across footer, contact overlay, and all page instances",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "social-links-valid",
    category: "Global Elements",
    title: "Social links are valid external URLs",
    description: "Social media links should point to valid external profiles",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "cta-buttons-linked",
    category: "Global Elements",
    title: "CTA buttons are linked",
    description: "All call-to-action buttons should have valid href destinations",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "no-empty-buttons",
    category: "Global Elements",
    title: "No empty button labels",
    description: "All buttons should have non-empty accessible text",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "email-links-mailto",
    category: "Global Elements",
    title: "Email links use mailto:",
    description: "Email addresses in links should use the mailto: scheme",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "phone-links-tel",
    category: "Global Elements",
    title: "Phone links use tel:",
    description: "Phone numbers in links should use the tel: scheme",
    severity: "VERIFY",
    automatable: true,
  },
  // ── NAVIGATION & LINKS ───────────────────────────────────────────────────
  {
    id: "url-accessible",
    category: "Navigation & Links",
    title: "Site URL is accessible",
    description: "The main URL should return a successful HTTP response",
    severity: "CRITICAL",
    automatable: true,
  },
  {
    id: "no-404-pages",
    category: "Navigation & Links",
    title: "No 404 pages found",
    description: "All scanned pages should return successful status codes",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "no-broken-internal-links",
    category: "Navigation & Links",
    title: "No broken internal links",
    description: "Internal links should not point to non-existent pages",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "external-links-valid-format",
    category: "Navigation & Links",
    title: "External links have valid format",
    description: "External links should be properly formed URLs",
    severity: "VERIFY",
    automatable: true,
  },
  // ── HOMEPAGE ─────────────────────────────────────────────────────────────
  {
    id: "homepage-hero-exists",
    category: "Homepage",
    title: "Hero/opener section exists",
    description: "Homepage should have a hero image, video, headline, and CTA",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "homepage-h1-exists",
    category: "Homepage",
    title: "Homepage has H1 heading",
    description: "Main heading (H1) should be present on the homepage",
    severity: "REQUIRED",
    automatable: true,
  },
  // ── ABOUT / AGENT / TEAM ─────────────────────────────────────────────────
  {
    id: "about-page-contact-info",
    category: "About / Agent / Team",
    title: "About page has contact info",
    description: "Agent/team bio pages should display accurate contact information",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── SEO ──────────────────────────────────────────────────────────────────
  {
    id: "page-title-exists",
    category: "SEO",
    title: "Page has title",
    description: "Every page should have an <title> element",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "page-title-length",
    category: "SEO",
    title: "Title length 45–61 chars",
    description: "Page titles should be 45–61 characters for optimal SEO",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "unique-page-titles",
    category: "SEO",
    title: "Page titles are unique",
    description: "Each page should have a distinct title — no duplicates",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "meta-description-exists",
    category: "SEO",
    title: "Meta description present",
    description: "Every page should have a meta description",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "unique-meta-descriptions",
    category: "SEO",
    title: "Meta descriptions are unique",
    description: "Each page's meta description should be distinct",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "h1-exists",
    category: "SEO",
    title: "H1 exists on each page",
    description: "Every page should have at least one H1 heading",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "og-image-exists",
    category: "SEO",
    title: "Open Graph image set",
    description: "Each page should have an og:image meta tag",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "canonical-valid",
    category: "SEO",
    title: "Canonical URL valid",
    description: "If a canonical URL is present, it should be a valid absolute URL",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "seo-image-human-review",
    category: "SEO",
    title: "SEO image matches page header",
    description: "Each page's SEO image should match the page header image — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── MOBILE / RESPONSIVE ──────────────────────────────────────────────────
  {
    id: "viewport-meta-exists",
    category: "Mobile / Responsive",
    title: "Viewport meta tag present",
    description: "Pages should have a responsive viewport meta tag",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "no-fixed-width-containers",
    category: "Mobile / Responsive",
    title: "No fixed-width inline containers",
    description: "Inline styles with fixed pixel widths may break mobile layout",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "mobile-visual-walkthrough",
    category: "Mobile / Responsive",
    title: "Mobile visual walkthrough completed",
    description: "Every page must be viewed on mobile — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── FORMS & LEAD ROUTING ─────────────────────────────────────────────────
  {
    id: "forms-have-inputs",
    category: "Forms & Lead Routing",
    title: "Forms have input fields",
    description: "All forms should contain named inputs with labels or placeholders",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "forms-have-submit",
    category: "Forms & Lead Routing",
    title: "Forms have submit button",
    description: "All forms should have a visible submit button",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "lead-routing-human-review",
    category: "Forms & Lead Routing",
    title: "Lead routing verified",
    description: "Form submission destinations (CRM/email) must be verified manually",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── IMAGE QUALITY ─────────────────────────────────────────────────────────
  {
    id: "images-not-broken",
    category: "Image Quality",
    title: "No broken images",
    description: "All <img> elements should have valid src attributes",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "images-have-alt",
    category: "Image Quality",
    title: "Images have alt text",
    description: "All meaningful images should have descriptive alt attributes",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "image-relevance-human-review",
    category: "Image Quality",
    title: "Image relevance to market/brand",
    description: "Images should match client's location, architectural style, and brand — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── COMPLIANCE ────────────────────────────────────────────────────────────
  {
    id: "prohibited-off-market-term",
    category: "Compliance",
    title: 'No "Off-Market" text',
    description: '"Off-Market" is prohibited and must not appear anywhere on the site',
    severity: "CRITICAL",
    automatable: true,
  },
  {
    id: "compliance-disclaimer-detected",
    category: "Compliance",
    title: "IDX/MLS disclaimer detected",
    description: "Sites with IDX should display required MLS/IDX disclaimers",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "license-number-detected",
    category: "Compliance",
    title: "License number present",
    description: "Agent license numbers (DRE, state license) should be present where required by law",
    severity: "VERIFY",
    automatable: true,
  },
  {
    id: "eho-realtor-logos",
    category: "Compliance",
    title: "EHO/Realtor logos in footer",
    description: "Equal Housing Opportunity and Realtor logos should be present in the footer — requires human review to confirm quality",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  {
    id: "brokerage-compliance-human-review",
    category: "Compliance",
    title: "Brokerage compliance verified",
    description: "Website must adhere to brokerage-specific branding rules — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  {
    id: "realtor-trademark-human-review",
    category: "Compliance",
    title: "Realtor® trademark usage",
    description: "Realtor® should be capitalized and used correctly — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── FINAL VALIDATION ─────────────────────────────────────────────────────
  {
    id: "404-legal-pages-present",
    category: "Final Validation",
    title: "404 and legal pages present",
    description: "A 404 page, Terms of Service, and Privacy Policy should exist",
    severity: "REQUIRED",
    automatable: true,
  },
  {
    id: "spelling-grammar-human-review",
    category: "Final Validation",
    title: "Spelling and grammar checked",
    description: "All pages should be reviewed with Grammarly or WordTune — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  {
    id: "content-migration-human-review",
    category: "Final Validation",
    title: "Content migration complete",
    description: "All agents, bios, properties, blogs, neighborhoods migrated from previous site — requires human review",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  // ── HANDOFF READINESS ─────────────────────────────────────────────────────
  {
    id: "handoff-chatter-post",
    category: "Handoff Readiness",
    title: "Chatter post with links and details",
    description: "Staging link, color palette, fonts, moodboard reference, and self-QA completion documented",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
  {
    id: "handoff-hidden-pages",
    category: "Handoff Readiness",
    title: "Hidden pages have indexing disabled",
    description: "Any page hidden from the frontend should have search indexing turned off",
    severity: "HUMAN_REVIEW",
    automatable: false,
  },
];

export const SCORE_IMPACTS: Record<string, number> = {
  CRITICAL: -10,
  REQUIRED: -5,
  VERIFY: -2,
  CONDITIONAL: -3,
  HUMAN_REVIEW: 0,
};

/**
 * PRIORITY_PATHS is no longer used for crawling.
 * Expected pages are now driven by AuditProfile via expected-routes.ts.
 * Kept for backward compatibility in case other code references it.
 * @deprecated Use getExpectedRouteUrls(profile, origin) from expected-routes.ts instead.
 */
export const PRIORITY_PATHS: string[] = [];
